name: Daily Geocode Student Outlets

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows for manual triggering of the workflow

jobs:
  geocode:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This line grants write permission
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas googlemaps

      - name: Run geocoding script and update CSV
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python scripts/geocode.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/outlets.csv
          git commit -m "Automated: Update geocoded student outlets CSV"
          git push